// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSnvUNtqeKa0ntijbbCkCi7mZi1Zh3uPo',
    appId: '1:883268695926:web:5af686bfc9353182faac57',
    messagingSenderId: '883268695926',
    projectId: 'dsp-projekt-2f588',
    authDomain: 'dsp-projekt-2f588.firebaseapp.com',
    storageBucket: 'dsp-projekt-2f588.firebasestorage.app',
    measurementId: 'G-50ZMDD9YJE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeKhXSG8VP7pLPhPE5cL0o2beR4W_CtT0',
    appId: '1:883268695926:android:4ca512e394e81dc4faac57',
    messagingSenderId: '883268695926',
    projectId: 'dsp-projekt-2f588',
    storageBucket: 'dsp-projekt-2f588.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSnvUNtqeKa0ntijbbCkCi7mZi1Zh3uPo',
    appId: '1:883268695926:web:f7822d3c6a13e706faac57',
    messagingSenderId: '883268695926',
    projectId: 'dsp-projekt-2f588',
    authDomain: 'dsp-projekt-2f588.firebaseapp.com',
    storageBucket: 'dsp-projekt-2f588.firebasestorage.app',
    measurementId: 'G-H3MM8CP228',
  );

}